### ISSUE TITLE
Error to run a test swf file

### ISSUE THREAD

**Issue by hydra1983** [joa/apparat#3]
console output:

```
[exec] java.lang.NoSuchMethodException:jitb.lang.Test.main([Ljava.lang.String;)
[exec]     at java.lang.Class.getMethod(Class.java:1607)
[exec]     at apparat.jitb.JITB$$anonfun$run$4.apply(JITB.scala:155)
```

source:

``` as3
package
{
    public class Test
    {
        public static function main(...args):void{
            trace("hello world!");
        }
    }
}
```

build with flash builder 4.7, sdk 4.6.0

**Comment by joa** [comment]
Toplevel classes are lifted to jitb.lang so if you define foo.Test it should work. Since JITB is no longer in development this issue won't be fixed.

**Comment by hydra1983** [comment]
there is a project on github called [shumway](https://github.com/mozilla/shumway), seems do the smiliar stuff like jitb with js.
